### ISSUE TITLE
❓ [ERROR]: خطا اجرا در اندروید 12

### ISSUE THREAD

**Issue by AHHasanian** [pusheco/pushe-flutter#33]
<div dir='rtl'>

[//]: # ([ERROR] و اموجی در تیتر برای وضوح مشکل ترجیحا باقی بماند)
[//]: # (لطفا حتما تمپلیت را رعایت کنید تا مشکل به خوبی توضیح داده شود و متون تمپلیت را پاک نکنید)

**شرح خطا**

بعد از اینکه پلاگین پوشه رو اضافه می کنم  ،  و می خواهم اپ در  اندروید 12 اجرا کنم با خطا زیر مواجه میشم (در اندروید های پایین تر خطا نمیده).

**لاگ خطا**

2022-04-29 13:23:16.852 12811-12811/com.example.flutter_push_notification_pushe E/Pushe: java.lang.IllegalArgumentException: com.example.flutter_push_notification_pushe: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at co.pushe.plus.fcm.v.e.get(FcmModule_ProvidesGeofencePendingIntentFactory.java:49)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at co.pushe.plus.fcm.w.d.get(FcmGeofenceManager_Factory.java:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at co.pushe.plus.fcm.v.a.b(DaggerFcmComponent.java:1)
        at co.pushe.plus.fcm.FcmInitializer.preInitialize(PusheInit.kt:18)
        at co.pushe.plus.internal.PusheInitializer.preInitializeComponents(PusheInitializer.kt:77)
        at co.pushe.plus.internal.PusheInitializer.initialize(PusheInitializer.kt:2)
        at co.pushe.plus.utils.InitProvider.onCreate(InitProvider.kt:1)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7422)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**اطلاعات محیط تست**
- نسخه‌ی پوشه یا پلاگین : pushe_flutter: ^2.5.2
- نسخه‌ی فریم‌ورک :  flutter  2.10.3
- سیستم‌عامل : Android
- TargetSDK/CompileSDK (Android) : 31

</div>

**Comment by mahdi-malv** [comment]
سلام
ممنون که اطلاع دادید
این باگ توی نسخه‌ی ۲.۶.۳ فیکس شده ولی هنوز پلاگین نسخه نیتیوش رو آپدیت نکرده

تا اون حین میتونید برید توی بخش build.gradle اندرویدتون و دپندنسی‌های اندروید رو آپدیت کنید.

**Comment by AHHasanian** [comment]
سلام  . 
خسته نباشید . 
 ممنون مشکل حل شد .
