### ISSUE TITLE
❓ [ERROR]: سوال

### ISSUE THREAD

**Issue by AHHasanian** [pusheco/pushe-flutter#34]
<div dir='rtl'>

[//]: # ([ERROR] و اموجی در تیتر برای وضوح مشکل ترجیحا باقی بماند)
[//]: # (لطفا حتما تمپلیت را رعایت کنید تا مشکل به خوبی توضیح داده شود و متون تمپلیت را پاک نکنید)

**شرح خطا**
سلام ، وقت بخیر .
بعد از اینکه پلاگین پوشه رو اضافه می کنم و اپ  اجرا میشه با خطا زیر مواجه میشم . ممنون میشم راهنمایی کنین .

**لاگ خطا**

</div>

```
2022-04-29 17:04:39.289 18031-18120/com.example.bahamberim E/FirebaseMessaging: Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: INVALID_SENDER. Won't retry the operation.
2022-04-29 17:04:39.306 18031-18096/com.example.bahamberim E/Pushe: No available service
2022-04-29 17:04:39.311 18031-18096/com.example.bahamberim E/Pushe: Pushe core module could not initialize
2022-04-29 17:04:39.312 18031-18096/com.example.bahamberim E/Pushe: Calling postInit of core FAILED
2022-04-29 17:04:39.313 18031-18096/com.example.bahamberim E/Pushe: co.pushe.plus.messaging.NoAvailableCourierException: No available courier is found
        at co.pushe.plus.RegistrationManager.a(RegistrationManager.kt:7)
        at co.pushe.plus.-$$Lambda$lifryXpW6dzR8da7lReV9E0CQbY.subscribe(Unknown Source:2)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:47)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
        at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:287)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at co.pushe.plus.internal.c.a(Schedulers.kt:1)
        at co.pushe.plus.internal.-$$Lambda$0jCndrCQbtmwrGMslpkCto7O2Nk.run(Unknown Source:4)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

<div dir='rtl'>

**اطلاعات محیط تست**
- نسخه‌ی پوشه یا پلاگین : pushe_flutter: ^2.6.3
- نسخه‌ی فریم‌ورک : flutter 2.10.3
- سیستم‌عامل : Android
- TargetSDK/CompileSDK (Android) : 31

</div>

**Comment by mahdi-malv** [comment]
سلام.
ارور از سمت Firebase messaging هست که به senderId گیر داده
احتمال داره پروژه‌ی فایربیس مشکل داشته باشه یا sender Id که توی توکن هست مشکل داشته باشه

**Comment by AHHasanian** [comment]
سلام . 
خسته نباشید . 
ممنون.
