### ISSUE TITLE
 Obtaining FCM token failed Bug

### ISSUE THREAD

**Issue by ParsaGachkar** [pusheco/pushe-flutter#5]
```
E/Pushe   (23437): Obtaining FCM token failed: Attempt to invoke virtual method 'java.lang.Object com.google.firebase.FirebaseApp.get(java.lang.Class)' on a null object reference
E/Pushe   (23437): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.google.firebase.FirebaseApp.get(java.lang.Class)' on a null object reference
E/Pushe   (23437): 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.0.0:2)
E/Pushe   (23437): 	at co.ronash.pushe.task.tasks.a.a(Unknown Source:21)
E/Pushe   (23437): 	at co.ronash.pushe.task.e.a(Unknown Source:87)
E/Pushe   (23437): 	at co.ronash.pushe.task.b.a.a.onRunJob(Unknown Source:24)
E/Pushe   (23437): 	at com.evernote.android.job.Job.runJob(Job.java:124)
E/Pushe   (23437): 	at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
E/Pushe   (23437): 	at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
E/Pushe   (23437): 	at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
E/Pushe   (23437): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Pushe   (23437): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Pushe   (23437): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Pushe   (23437): 	at java.lang.Thread.run(Thread.java:764)
W/Pushe   (23437): Too many initialize calls made, skipping reinitialization
I/System.out(23437): [Plugin] Trying to initialize Pushe
W/Pushe   (23437): Too many initialize calls made, skipping reinitialization
```

I see this log when i'm running
`Pushe.initialize(showDialog: true);`
I'm using pushe: ^1.0.1

configured according to readme file

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

توی استک‌تریس دارم **firebase-iid@@20.0.0** رو می‌بینم.

احتمال داره که با iid مشکلاتی داشته‌باشه.

آیا شما از سرویس دیگه‌ای استفاده کردید؟
مثلا Firebase Auth, ... که اومده و نسخه‌ی 20 رو اضافه کرده؟

باید نسخه‌ی 20 رو با پلاگین تست کنم که آیا تغییراتی توی API داشته یانه.

لطفا در مورد لایبرری‌هایی که استفاده کردید و ابزاری که نسبت به سورس خالی اضافه دارید اطلاعاتی در اختیار بنده قرار بدید تا بیشتر در مورد مشکل بدونم.

</div>

**Comment by ParsaGachkar** [comment]
Firebase auth نه فقط ی کتابخونه دارم که از mlkit استفاده میکنه اونم local
بخش dependencies فایل pubspec.yaml م اینطوریه
‍‍‍```
dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: 0.5.1
  flare_flutter: ^1.5.4
  #fast_qr_reader_view:
    #git:
      #url: https://github.com/facundomedica/fast_qr_reader_view.git
  fast_qr_reader_view:
    path: ../fast_qr_reader_view-costomized/
  fluttertoast: 3.1.3
  font_awesome_flutter: 8.5.0
  package_info: ^0.4.0+3
  intl:
  flutter_masked_text:
  contacts_service: ^0.3.4
  keyboard_avoider: 0.1.2
  permission_handler: '^3.2.0'
  code_input: ^1.0.3
  url_launcher: ^5.1.4
  flutter_secure_storage:
  image_picker: 0.6.1+4
  flutter_svg: 0.14.1
  audioplayers:
  vibration: 1.2.1
  photo_view:
  http: 0.12.0+2
  image:
  connectivity: 0.4.4
  shamsi_date: ^0.5.5
  draggable_scrollbar: 0.0.4
  persian_datetime_picker: ^0.0.1
  share: 0.6.2+4
  signalr_client: 0.1.6
  flutter_local_notifications: 0.8.4
  pushe: ^1.0.1
```

**Comment by ParsaGachkar** [comment]
مشکل حل نشده هنوز؟

**Comment by ParsaGachkar** [comment]
سلام من ۹ روزه درخواست پشیبانی دادم از طریق ایمیل لطفا اگه امکانش هست راهنمایی کنید. این مشکل باید حل بشه برای من

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
عذرخواهی می‌کنم که دیر پاسخ می‌دم.

من کیس مشابه رو بررسی کردم و اروری که داشتید برای من رخ نداد.
پروژه‌ی سمپل رو توی یه مخزن پوش کردم لطفا کلون کنید و تست کنید ببینید مشکل توی این سمپل هم برای شما وجود داره و در صورتی که مورد شما چیزی (از نظر لایبرری و ...) از سمپلی که من قرار دادم بیشتر داره اون رو به سمپل اضافه کنید و پوش کنید تا بنده بیشتر در مورد مشکل مطلع بشم.

</div>

[Sample project](https://gitlab.com/mahdi-malv/flutter_test_1)

**Comment by ParsaGachkar** [comment]
کتابخونه ی #fast_qr_reader_view: رو کامنت کردین تو yaml  من یکم تغییرات داده بودم بهش زیر همون import ش کرده بودم. همین کتابخونس از MlKit‌استفاده میکنه. فک کنم نسخه firebaseش تداخل داره با نسخه ای که شما استفاده میکنید. راستی من فایربیس ۲۰ رو حذف کردم مشکل حل نشد.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سورسی که من فرستادم رو میشه تست کنید ببنید اون براتون نصب ثبت می‌کنه یا نه؟

</div>

**Comment by mahdi-malv** [comment]
Closing due to inactivity. Feel free to reopen if it still exists in the new versions.
